name: Build Acumatica Customization

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to (e.g. Dev, QA, Prod)'
        required: true
        default: 'Dev'
      branch:
        description: 'Git branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: self-hosted

    env:
      SOLUTION: 'AcumaticaUSSFenceCustomizations[2024R1].sln'
      PROJECT: 'AcumaticaUSSFenceCustomizations[2024R1]\AcumaticaUSSFenceCustomizations[2024R1].csproj'
      ZIP_OUTPUT: 'AcumaticaUSSFenceCustomizations[2024R1].zip'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install NuGet CLI
        uses: NuGet/setup-nuget@v1

      # - name: Restore (if using NuGet)
      #   run: nuget restore $env:SOLUTION

      - name: Copy Bin files from Acumatica instance (with fallback logging)
        shell: pwsh
        run: |
          $source = "C:\Program Files\Acumatica ERP\USSFence\Bin"
          $destination = "AcumaticaUSSFenceCustomizations[2024R1]\bin\Release"

          Write-Host "🔍 Checking source path: $source"
          if (Test-Path $source) {
           Write-Host "✅ Source path exists."
            New-Item -ItemType Directory -Force -Path $destination | Out-Null
            Copy-Item -Path "$source\*" -Destination $destination -Force -Recurse
            Write-Host "✅ Files copied to $destination"
          } else {
            Write-Host "❌ Source path not found: $source"
            Get-ChildItem "C:\Program Files\Acumatica ERP\" -Recurse -Directory | Where-Object Name -like "*USSFence*" | Format-List FullName
            throw "❌ Cannot find source path: $source"
          }

      - name: Restore NuGet packages
        run: nuget restore $env:SOLUTION
        shell: pwsh
        env:
          SOLUTION: AcumaticaUSSFenceCustomizations[2024R1].sln
          NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages

      - name: Build Project
        run: msbuild $env:PROJECT /p:Configuration=Release
        shell: pwsh
        env:
          PROJECT: AcumaticaUSSFenceCustomizations[2024R1]\AcumaticaUSSFenceCustomizations[2024R1].csproj
          NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages

      - name: Copy DLL to Customization Bin
        shell: pwsh
        run: |
          $projectName = "AcumaticaUSSFenceCustomizations`[2024R1`]"
          $dllName = "AcumaticaUSSFenceCustomizations[2024R1].dll"

          # Full source path
          $source = Join-Path -Path $PWD.Path -ChildPath "$projectName\bin\Release"

          # Destination inside the Customizations folder
          $destination = Join-Path -Path $PWD.Path -ChildPath "Customizations\$projectName\$projectName\Bin"

          Write-Host "🔁 Copying built DLL from: $source"
          Write-Host "➡️ Destination path: $destination"

          
          # Check the contents of the 'bin\Release' folder
          Write-Host "🔎 Listing files in $source"
          Get-ChildItem -LiteralPath $source | Select-Object FullName

          # Safety check before copying
          if (Test-Path -LiteralPath $source) {
              New-Item -ItemType Directory -Force -Path $destination | Out-Null
              Copy-Item -LiteralPath (Join-Path $source $dllName) -Destination $destination -Force
              Write-Host "✅ DLL copied to $destination"
          } else {
              Write-Host "❌ Source path not found: $source"
              Get-ChildItem -Recurse | Where-Object { $_.Name -like "*.dll" } | Format-Table FullName
          }

      - name: Create ZIP Package
        run: |
          Compress-Archive -Path "Customizations\AcumaticaUSSFenceCustomizations[2024R1]\*" `
            -DestinationPath $env:ZIP_OUTPUT -Force

      # - name: Publish to Acumatica Dev
      #   run: |
      #     pwsh ./scripts/publishCustomization.ps1 `
      #       -zipPath $env:ZIP_OUTPUT `
      #       -instanceUrl "${{ secrets.ACU_DEV_URL }}" `
      #       -username "${{ secrets.ACU_USERNAME }}" `
      #       -password "${{ secrets.ACU_PASSWORD }}"
